/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as EmployeesRegisterRouteImport } from './routes/employees/register'
import { Route as EmployeesDepartmentsRouteImport } from './routes/employees/departments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRegisterRoute = EmployeesRegisterRouteImport.update({
  id: '/employees/register',
  path: '/employees/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesDepartmentsRoute = EmployeesDepartmentsRouteImport.update({
  id: '/employees/departments',
  path: '/employees/departments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/employees/departments': typeof EmployeesDepartmentsRoute
  '/employees/register': typeof EmployeesRegisterRoute
  '/employees/': typeof EmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/employees/departments': typeof EmployeesDepartmentsRoute
  '/employees/register': typeof EmployeesRegisterRoute
  '/employees': typeof EmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/employees/departments': typeof EmployeesDepartmentsRoute
  '/employees/register': typeof EmployeesRegisterRoute
  '/employees/': typeof EmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/employees/departments'
    | '/employees/register'
    | '/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/employees/departments'
    | '/employees/register'
    | '/employees'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/employees/departments'
    | '/employees/register'
    | '/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  EmployeesDepartmentsRoute: typeof EmployeesDepartmentsRoute
  EmployeesRegisterRoute: typeof EmployeesRegisterRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/register': {
      id: '/employees/register'
      path: '/employees/register'
      fullPath: '/employees/register'
      preLoaderRoute: typeof EmployeesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/departments': {
      id: '/employees/departments'
      path: '/employees/departments'
      fullPath: '/employees/departments'
      preLoaderRoute: typeof EmployeesDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  EmployeesDepartmentsRoute: EmployeesDepartmentsRoute,
  EmployeesRegisterRoute: EmployeesRegisterRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
